# Generated by Django 4.1.5 on 2023-02-17 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_post_tags"),
    ]

    operations = [
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=64)),
                ("url", models.URLField()),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
