# Generated by Django 4.1.5 on 2023-02-17 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_video"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="video",
            name="url",
        ),
        migrations.AddField(
            model_name="video",
            name="link",
            field=models.CharField(default="helo", max_length=64),
            preserve_default=False,
        ),
    ]
